-- 1번
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", 
EXTRACT(YEAR FROM ENTRANCE_DATE ) ||'-'|| 
EXTRACT(MONTH FROM ENTRANCE_DATE )||'-'|| 
EXTRACT(DAY FROM ENTRANCE_DATE ) "입학년도"
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;

--2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3번
SELECT PROFESSOR_NAME "교수이름", 
((EXTRACT(YEAR FROM SYSDATE)-('19'||SUBSTR(PROFESSOR_SSN,1,2)))) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
ORDER BY PROFESSOR_SSN DESC;

--4번
SELECT SUBSTR(PROFESSOR_NAME,2) "이름" 
FROM TB_PROFESSOR;

--5번
SELECT STUDENT_NO,STUDENT_NAME 
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - (EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2), 'RR'))) > 19;

--6번
SELECT TO_CHAR(TO_DATE('2020-12-25'),'DAY') FROM DUAL;

--7번
/*
TO_DATE('99/10/11', 'YY/MM/DD') 2099
TO_DATE('49/10/11', 'YY/MM/DD') 2049
TO_DATE('99/10/11', 'RR/MM/DD') 1999
TO_DATE('49/10/11', 'RR/MM/DD') 2049
*/

--8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9번
SELECT ROUND(AVG(POINT),1) 평점 
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10번
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)" 
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12번
SELECT SUBSTR(TERM_NO,1,4) "년도" , ROUND(AVG(POINT),1) "년도별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);

--13번
SELECT DEPARTMENT_NO 학과코드명, COUNT(DECODE(ABSENCE_YN  , 'Y', 1)) "휴학생 수"
FROM TB_STUDENT
--WHERE ABSENCE_YN  = 'Y'
GROUP BY DEPARTMENT_NO;

--14번
SELECT STUDENT_NAME 동일이름, COUNT(*) "동일인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >= 2;

--15번
SELECT SUBSTR(TERM_NO,1,4) "년도" , SUBSTR(TERM_NO,5,2) "학기", ROUND(AVG(POINT),1) "년도별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2));
