-- 1번
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지 
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;

--2번
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN ASC;

--3번
SELECT STUDENT_NAME 학생이름,STUDENT_NO 학번, STUDENT_ADDRESS 주소지
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%강원도%' 
OR STUDENT_ADDRESS LIKE '%경기도%'
AND SUBSTR(STUDENT_NO,1,1) != 'A'
ORDER BY STUDENT_NAME ASC;

--4번
SELECT * FROM TB_DEPARTMENT;
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = 005
ORDER BY PROFESSOR_SSN ASC;

--5번
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = 200402
AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC;

--6번
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT S
LEFT JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
--ORDER BY STUDENT_NAME ASC
;

--7번
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
LEFT JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO);

--8번
SELECT CLASS_NAME, PROFESSOR_NAME 
FROM TB_CLASS_PROFESSOR CP
JOIN TB_CLASS C ON (CP.CLASS_NO = C.CLASS_NO)
JOIN TB_PROFESSOR P ON (CP.PROFESSOR_NO = P.PROFESSOR_NO)
;

--9번
SELECT CLASS_NAME, PROFESSOR_NAME 
FROM TB_CLASS_PROFESSOR CP
LEFT JOIN TB_CLASS C ON (CP.CLASS_NO = C.CLASS_NO)
LEFT JOIN TB_PROFESSOR P ON (CP.PROFESSOR_NO = P.PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.CATEGORY = '인문사회';

--10번
SELECT S.STUDENT_NO 학번, STUDENT_NAME "학생이름", ROUND(AVG(POINT),1) "전체 평점"
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO) 
WHERE D.DEPARTMENT_NAME = '음악학과'
GROUP BY S.STUDENT_NO, STUDENT_NAME
ORDER BY S.STUDENT_NO ASC;

--11번
SELECT DEPARTMENT_NAME 학과이름 , STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE STUDENT_NO ='A313047';

--12번
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT S
JOIN TB_GRADE G ON(S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_CLASS C ON(G.CLASS_NO = C.CLASS_NO)
WHERE TERM_NO LIKE '%2007%'
AND C.CLASS_NAME = '인간관계론';

--13번
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_DEPARTMENT D
JOIN TB_CLASS C ON (D.DEPARTMENT_NO = C.DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR CP ON (C.CLASS_NO = CP.CLASS_NO)
WHERE CATEGORY ='예체능'
AND CP.CLASS_NO IS NULL
ORDER BY DEPARTMENT_NAME;

--14번 020
SELECT STUDENT_NAME AS 학생이름 , NVL(PROFESSOR_NAME,'지도교수 미지정') AS 지도교수
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE S.DEPARTMENT_NO = 20
ORDER BY STUDENT_NO ASC;

--15번
SELECT S.STUDENT_NO AS 학번, S.STUDENT_NAME AS 이름, 
D.DEPARTMENT_NAME AS "학과 이름", ROUND(AVG(G.POINT),5) AS 평점
FROM TB_STUDENT S
LEFT JOIN TB_DEPARTMENT D 
        ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
LEFT JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE S.ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME,D.DEPARTMENT_NAME
HAVING AVG(G.POINT) >= 4.0
ORDER BY AVG(G.POINT) DESC;

-- 16번