--1
INSERT INTO TB_CLASS_TYPE 
VALUES('01','전공필수');
INSERT INTO TB_CLASS_TYPE 
VALUES('02','전공선택');
INSERT INTO TB_CLASS_TYPE 
VALUES('03','교양필수');
INSERT INTO TB_CLASS_TYPE 
VALUES('04','교양선택');
INSERT INTO TB_CLASS_TYPE 
VALUES('05','논문지도');

--2

