--1 
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

--2 
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

--3
ALTER TABLE TB_CATEGORY
ADD CONSTRAINT NPK PRIMARY KEY TO(NAME);

--4
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL;

--5
ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10)
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

--6 
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

--7 
ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT NPK1 TO PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT NPK2 TO PK_CLASS_TYPE_NAME;

--8
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

--9
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY
FOREIGN KEY (CATEGORY)
REFERENCES TB_CATEGORY(CATEGORY_NAME);

--10
CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO "학번", STUDENT_NAME "학생이름",STUDENT_ADDRESS "주소" 
FROM TB_STUDENT;
DROP VIEW VW_학생일반정보;

SELECT * FROM VW_학생일반정보;

--11
CREATE VIEW VW_지도면담
AS SELECT STUDENT_NAME "학생이름", D.DEPARTMENT_NAME "학과이름", NVL(P.PROFESSOR_NAME,'지도교수 없음') "지도교수이름"
FROM TB_STUDENT S
LEFT JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR P ON(S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
ORDER BY 2;

DROP VIEW VW_지도면담;
SELECT * FROM VW_지도면담;

--12
CREATE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(STUDENT_NO) "STUDENT_COUNT"
FROM TB_DEPARTMENT D
LEFT JOIN TB_STUDENT S ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO) 
GROUP BY DEPARTMENT_NAME;

SELECT * FROM VW_학과별학생수;

--13
UPDATE VW_학생일반정보
SET 학생이름 = '김동욱'
WHERE 학번 = 'A213046';

SELECT * FROM VW_학생일반정보;

--14
CREATE OR REPLACE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(STUDENT_NO) "STUDENT_COUNT"
FROM TB_DEPARTMENT D
LEFT JOIN TB_STUDENT S ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO) 
GROUP BY DEPARTMENT_NAME 
WITH READ ONLY;
--15 2009 2008 2007 2006 2005
SELECT * FROM(
SELECT CLASS_NO "과목번호", CLASS_NAME "과목이름", COUNT(*)
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
WHERE 2009 - SUBSTR(TERM_NO,1,4) < 5
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 3 DESC
)
WHERE ROWNUM <=3;

